CREATE TABLE tb_payment
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       BIGINT                   NOT NULL,
    user_id        BIGINT                   NOT NULL,
    amount         DECIMAL                  NOT NULL,
    payment_method VARCHAR(20),
    status         VARCHAR(20)              NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL
);